using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Bullet : MonoBehaviour
{
    public Animator animator;
    public Rigidbody rb; // Referŕncia para o Rigidbody da bala
    private bool isHit = false; // Flag para garantir que a animašŃo de impacto sˇ seja chamada uma vez

    // Start is called before the first frame update
    void Start()
    {
        animator = GetComponent<Animator>();
        rb = GetComponent<Rigidbody>();
    }

    // Update is called once per frame
    void Update()
    {
        // Se a bala tiver colidido, paramos o movimento dela
        if (isHit)
        {
            rb.velocity = Vector3.zero; // Para o movimento
        }
    }

    private void OnTriggerEnter(Collider col)
    {
        if (!isHit && col.CompareTag("Inimigo"))
        {
            isHit = true;
            animator.SetTrigger("hit"); // Ativa a animašŃo de explosŃo
        }
    }

    public void Destroy()
    {
        Destroy(gameObject);
    }



}
